name:                rebootable
version:             0.1.0.0
github:              "githubuser/rebootable"
license:             BSD3
author:              "Yutaka Nishimura"
maintainer:          "ytk.nishimura@gmail.com"
copyright:           "2018 Yutaka Nishimura"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/rebootable#readme>

dependencies:
- base >= 4.7 && < 5
- warp
- wai
- http-types
- directory
- bytestring
- yaml
- raw-strings-qq
- text

library:
  source-dirs: src

executables:
  rebootable-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rebootable

tests:
  rebootable-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rebootable
